# Generated by Django 5.2 on 2025-04-19 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VozComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando_recibido', models.TextField()),
                ('resultado_accion', models.TextField(blank=True, null=True)),
                ('fecha_comando', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.user')),
            ],
            options={
                'db_table': 'voz_comandos',
            },
        ),
    ]
