# Generated by Django 5.2 on 2025-04-22 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago (módulo pagos)', 'verbose_name_plural': 'Pagos (módulo pagos)'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_payments', related_query_name='pagos_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
