# Generated by Django 5.2 on 2025-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
